version: '3.9'

services:
  postgres:
    image: postgres:13
    restart: unless-stopped
    container_name: team-util-monitor
    env_file: .env
    environment:
      POSTGRES_USER: icreatesoftware
      POSTGRES_PASSWORD: icreatesoftware
      POSTGRES_DB: icreatesoftware
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    ports:
      - 5433:5432
    networks:
      - icreatesoftware-private


volumes:
  postgres-data:

networks:
  icreatesoftware-private:
