version: '3.4'

services:
  web:
    image: polar-thicket-16073
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 6565:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules


volumes:
  postgres-auth-data:

networks:
  icreatesoftware-private:
